import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";
import { WalletComponents } from "./components/Wallet";
import SwapComponents from "./components/Swap";
import { Token } from "@coinbase/onchainkit/token";
import TokenTable from "./components/TokenTable";

const USDCToken: Token = {
  address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  chainId: 8453,
  decimals: 6,
  name: "USDC",
  symbol: "USDC",
  image:
    "https://dynamic-assets.coinbase.com/3c15df5e2ac7d4abbe9499ed9335041f00c620f28e8de2f93474a9f432058742cdf4674bd43f309e69778a26969372310135be97eb183d91c492154176d455b8/asset_icons/9d67b728b6c8f457717154b3a35f9ddc702eae7e76c4684ee39302c4d7fd0bb8.png",
};

export default function Home() {
  const {
    data: tokens,
    isLoading,
    error,
  } = api.coingecko.getTokens.useQuery({
    sparkline: false,
  });
  const [inputToken, setInputToken] = useState<Token>(USDCToken);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <WalletComponents />
          <SwapComponents inputToken={inputToken} />
          {isLoading && <p>Loading tokens...</p>}
          {error && <p>Error loading tokens: {error.message}</p>}
          {tokens && <TokenTable onTokenSelected={setInputToken} tokens={tokens} />}
        </div>
      </main>
    </>
  );
}
